name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MERN Project
        uses: actions/checkout@v3

      - name: Checkout DevOps Repo (to get Dockerfiles)
        uses: actions/checkout@v3
        with:
          repository: affanaslam24/deploy-dockerfiles
          path: devops

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/demodocker-backend:latest -f devops/backend.Dockerfile Backend
          docker push ${{ secrets.DOCKER_USERNAME }}/demodocker-backend:latest

      - name: Build & Push Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/demodocker-frontend:latest -f devops/frontend.Dockerfile Frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/demodocker-frontend:latest

  deploy:
    name: Deploy to AWS VPS
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/demodocker-backend:latest
            docker pull ${{ secrets.DOCKER_USERNAME }}/demodocker-frontend:latest

            docker stop backend || true
            docker stop frontend || true
            
            docker rm backend || true
            docker rm frontend || true

            docker run -d --name backend -p 5555:5555 -e MONGODB_URL="${{ secrets.MONGODB_URL }}" ${{ secrets.DOCKER_USERNAME }}/demodocker-backend:latest
            docker run -d --name frontend -p 5175:5175 ${{ secrets.DOCKER_USERNAME }}/demodocker-frontend:latest
